### ISSUE TITLE
- waiting for device -

### ISSUE THREAD

**Issue by codexprime** [LimerBoy/ADB-Hunter#2]
Работает отлично, но вот при запуске инсталлера, утыкается в:

error: device offline
- waiting for device 

и молчит 

Подскажи пожалуйста как это дело обойти ? что бы просто пропускать девайсы на которые надо ждать

**Comment by LimerBoy** [comment]
Покажите инфо о вашей ос, версия питона, версия adb

**Comment by codexprime** [comment]
Kali Linux - 2020.2
Python 2.7.18 
Python 3.8.3
Android Debug Bridge version 1.0.39
Version 1:8.1.0+r23-7

**Comment by codexprime** [comment]
обновли ADB с офф сайта в ручную 
спасибу за подсказку
